// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Gi41jS2gbGy5q0DfoUNH2reESoo2amM',
    appId: '1:813269010576:web:52c1753def7bcdecb4f015',
    messagingSenderId: '813269010576',
    projectId: 'lostxfound',
    authDomain: 'lostxfound.firebaseapp.com',
    storageBucket: 'lostxfound.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxEopDXabsq2jDy61KJDuYsmph03NUdMo',
    appId: '1:813269010576:android:cf4ebd48c7e6796bb4f015',
    messagingSenderId: '813269010576',
    projectId: 'lostxfound',
    storageBucket: 'lostxfound.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNJZLXcrM9gifw0pyx13Zz6C9YrvYGCyM',
    appId: '1:813269010576:ios:e3420e946c2b7cd1b4f015',
    messagingSenderId: '813269010576',
    projectId: 'lostxfound',
    storageBucket: 'lostxfound.appspot.com',
    iosBundleId: 'com.example.lostxfoundFront',
  );
}
